# Generated by Django 5.0.3 on 2024-03-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(blank=True, null=True, related_name='workspaces', to='auth.group', verbose_name='groupes')),
            ],
            options={
                'verbose_name': 'Partitionnement',
            },
        ),
    ]
