# Generated by Django 5.0.3 on 2024-03-13 14:31

import django.db.models.deletion
import django_admin_workflow.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=8)),
                ('verbose_name', models.CharField(max_length=40)),
                ('bgcolor', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status values',
            },
        ),
        migrations.CreateModel(
            name='ConfigRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_space', models.BooleanField(default=True)),
                ('filter_user', models.BooleanField(default=False)),
                ('role', models.ForeignKey(limit_choices_to=django_admin_workflow.models._get_role_groups, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Role config',
            },
        ),
        migrations.CreateModel(
            name='ConfigRoleAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_fields', models.CharField(blank=True, max_length=80, null=True)),
                ('readonly_fields', models.CharField(blank=True, max_length=80, null=True)),
                ('config_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_add', to='django_admin_workflow.configrole')),
            ],
            options={
                'verbose_name': 'Role/add config',
            },
        ),
        migrations.CreateModel(
            name='ConfigRoleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_fields', models.CharField(blank=True, max_length=80, null=True)),
                ('readonly_fields', models.CharField(blank=True, max_length=80, null=True)),
                ('config_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_configs', to='django_admin_workflow.configrole')),
                ('permission', models.ForeignKey(limit_choices_to=django_admin_workflow.models.get_workflow_permissions, on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_admin_workflow.status')),
            ],
            options={
                'verbose_name': 'Role/status config',
            },
        ),
        migrations.CreateModel(
            name='ConfigWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='main', max_length=40)),
                ('ctype', models.ForeignKey(limit_choices_to=django_admin_workflow.models.get_workflow_contenttypes, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Workflow',
            },
        ),
        migrations.AddField(
            model_name='configrole',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_admin_workflow.configworkflow', verbose_name='workflow'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=8)),
                ('verbose_name', models.CharField(max_length=40)),
                ('bgcolor', models.CharField(blank=True, max_length=20, null=True)),
                ('ctype', models.ForeignKey(limit_choices_to=django_admin_workflow.models.get_workflow_contenttypes, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=40, null=True)),
                ('group', models.ForeignKey(blank=True, help_text='laisser vide sauf cas spécifique', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='auth.group', verbose_name='groupe associé')),
            ],
            options={
                'verbose_name': 'Espace',
            },
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='all', max_length=40)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifier_configs', to='auth.group')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_admin_workflow.space')),
            ],
        ),
        migrations.CreateModel(
            name='RoleStatusAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=8)),
                ('verbose_name', models.CharField(max_length=40)),
                ('config_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_admin_workflow.configrolestatus')),
                ('status_change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_admin_workflow.status')),
            ],
            options={
                'verbose_name': 'Action',
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('reactive_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notif_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Settings',
            },
        ),
    ]
