# Generated by Django 5.0.3 on 2024-03-11 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_admin_workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('status_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_admin_workflow.status')),
            ],
            options={
                'verbose_name': 'Role',
            },
            bases=('django_admin_workflow.status',),
        ),
        migrations.AlterField(
            model_name='space',
            name='group',
            field=models.ForeignKey(blank=True, help_text='laisser vide sauf cas spécifique', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='auth.group', verbose_name='groupe associé'),
        ),
    ]
