# Generated by Django 5.0.3 on 2024-03-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_admin_workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='groups',
            field=models.ManyToManyField(related_name='workspaces', to='auth.group', verbose_name='groupes'),
        ),
    ]
