# Generated by Django 5.0.3 on 2024-03-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_workflow', '0002_alter_space_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='label',
            field=models.CharField(default='main', max_length=40),
        ),
    ]
