# Generated by Django 5.0.3 on 2024-03-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_workflow', '0002_rolepermission_alter_space_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'verbose_name': 'Espace'},
        ),
    ]
