# Generated by Django 5.0.3 on 2024-03-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_workflow', '0002_remove_configrolestatus_config_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='bgcolor',
            field=models.CharField(default='LightGray', max_length=20),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='bgcolor',
            field=models.CharField(default='LightGray', max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
    ]
