# Generated by Django 5.0.3 on 2024-03-14 19:31

import django.db.models.deletion
import django_admin_workflow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_admin_workflow', '0003_alter_status_options_alter_rolepermission_bgcolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='bgcolor',
            field=models.CharField(default='LightGray', max_length=20, verbose_name='bcolor'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='ctype',
            field=models.ForeignKey(limit_choices_to=django_admin_workflow.models.get_workflow_contenttypes, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='workflow model'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='slug',
            field=models.SlugField(max_length=20, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='verbose_name',
            field=models.CharField(max_length=40, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='space',
            name='group',
            field=models.ForeignKey(blank=True, help_text='laisser vide sauf cas spécifique', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='auth.group', verbose_name='linked group'),
        ),
        migrations.AlterField(
            model_name='status',
            name='bgcolor',
            field=models.CharField(default='LightGray', max_length=20, verbose_name='bcolor'),
        ),
        migrations.AlterField(
            model_name='status',
            name='slug',
            field=models.SlugField(max_length=20, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='status',
            name='verbose_name',
            field=models.CharField(max_length=40, verbose_name='label'),
        ),
    ]
