# Generated by Django 5.0.3 on 2024-03-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_workflow', '0004_alter_rolepermission_bgcolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='bgcolor',
            field=models.CharField(default='LightGray', help_text='HTML standard color name or #......', max_length=20, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='slug',
            field=models.SlugField(max_length=20, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='status',
            name='bgcolor',
            field=models.CharField(default='LightGray', help_text='HTML standard color name or #......', max_length=20, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='status',
            name='slug',
            field=models.SlugField(max_length=20, verbose_name='token'),
        ),
    ]
