# Generated by Django 5.0.3 on 2024-03-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_workflow', '0005_alter_rolepermission_bgcolor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersetting',
            old_name='active',
            new_name='email_active',
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='email_active',
            field=models.BooleanField(default=True),
        ),
    ]
