# Generated by Django 5.0.3 on 2024-03-10 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_space', models.BooleanField(default=True)),
                ('filter_user', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigRoleAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_fields', models.CharField(blank=True, max_length=80, null=True)),
                ('readonly_fields', models.CharField(blank=True, max_length=80, null=True)),
                ('config_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_add', to='config_workflow.configrole')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigRoleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_fields', models.CharField(blank=True, max_length=80, null=True)),
                ('readonly_fields', models.CharField(blank=True, max_length=80, null=True)),
                ('config_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_configs', to='config_workflow.configrole')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='main', max_length=40)),
                ('ctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='configrole',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_workflow.configworkflow'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=8)),
                ('verbose_name', models.CharField(max_length=40)),
                ('bgcolor', models.CharField(blank=True, max_length=20, null=True)),
                ('ctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='RoleStatusAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=8)),
                ('verbose_name', models.CharField(max_length=40)),
                ('config_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_workflow.configrolestatus')),
                ('status_change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config_workflow.status')),
            ],
        ),
        migrations.AddField(
            model_name='configrolestatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_workflow.status'),
        ),
    ]
