# Generated by Django 5.0.3 on 2024-03-10 18:34

import config_workflow.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('config_workflow', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configrole',
            options={'verbose_name': 'Role config'},
        ),
        migrations.AlterModelOptions(
            name='configroleadd',
            options={'verbose_name': 'Role/add config'},
        ),
        migrations.AlterModelOptions(
            name='configrolestatus',
            options={'verbose_name': 'Role/status config'},
        ),
        migrations.AlterModelOptions(
            name='configworkflow',
            options={'verbose_name': 'Workflow'},
        ),
        migrations.AlterModelOptions(
            name='rolestatusaction',
            options={'verbose_name': 'Action'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'permissions': [('can_edit', 'Editor role'), ('can_publish', 'Publisher role')], 'verbose_name': 'Status', 'verbose_name_plural': 'Status values'},
        ),
        migrations.AlterField(
            model_name='configrole',
            name='role',
            field=models.ForeignKey(limit_choices_to=config_workflow.models._get_role_groups, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='configrolestatus',
            name='permission',
            field=models.ForeignKey(limit_choices_to=config_workflow.models._get_workflow_permissions, on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='configworkflow',
            name='ctype',
            field=models.ForeignKey(limit_choices_to=config_workflow.models._get_workflow_contenttypes, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='status',
            name='ctype',
            field=models.ForeignKey(limit_choices_to=config_workflow.models._get_workflow_contenttypes, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
