# Generated by Django 5.0.3 on 2024-03-11 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_workflow', '0002_alter_configrole_options_alter_configroleadd_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status values'},
        ),
        migrations.AlterField(
            model_name='configrole',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_workflow.configworkflow', verbose_name='workflow'),
        ),
    ]
