# Generated by Django 5.0.3 on 2024-03-13 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apptest', '0001_initial'),
        ('django_admin_workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytestmodel',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_admin_workflow.space', verbose_name='space'),
        ),
    ]
