# Generated by Django 5.0.3 on 2024-03-16 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0003_alter_mytestmodel_status'),
        ('django_admin_workflow', '0005_alter_rolepermission_bgcolor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendmailExecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SlugField(help_text='status of objects to be processed', max_length=20)),
                ('last_run_datetime', models.DateTimeField(blank=True, null=True)),
                ('last_OK', models.BooleanField(default=False)),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_admin_workflow.space', verbose_name='space')),
            ],
            options={
                'verbose_name': 'Executor',
                'abstract': False,
            },
        ),
    ]
