# Generated by Django 5.0.3 on 2024-03-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0004_sendmailexecutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmailexecutor',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
