# Groupe clients
[clients]
    filter = "lambda q, user_space, user: q.filter(space=user_space)"

    # création d'un objet dans le workflow
    [clients.creation]
    fields =  ['name', 'contact', 'status']
    readonly_fields = ['contact', 'status']

    # Etat DRAFT
    [clients.DRAFT]
    fields =  ['name', 'contact', 'status']
    readonly_fields = ['contact', 'status']
    actions = [ ["save",     "Enregistrer"],
                ["can_submit",   "Soumettre", "submited"],
                ["can_cancel",   "Annuler",   "canceled"]]
    views_extra = [["do_something", "Do something (NYI)"]]
