# Groupe clients
[clients]
    filter = "lambda q, user_space, user: q.filter(space=user_space)"

    # création d'un objet dans le workflow
    [clients.creation]
    fields =  ['name', 'contact', 'status']
    readonly_fields = ['contact', 'status']

    # Etat DRAFT
    [clients.DRAFT]
    perms = ["can_submit"]
    fields =  ['name', 'contact', 'status']
    readonly_fields = ['contact', 'status']
    actions = [ ["save",     "Enregistrer"],
                ["submit",   "Soumettre", "submited"],
                ["submit",   "Soumettre", "accepted"],
                ["validate", "Valider",   "valid"],
                ["cancel",   "Annuler",   "canceled"]]

