# Generated by Django 5.0.3 on 2024-03-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('n', 'Nouveau'), ('a', 'Accepté'), ('v', 'Validé'), ('p', 'Publié')], default='n', max_length=1)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'permissions': [('can_submit', 'Rôle demandeur'), ('can_accept', 'Rôle accepteur'), ('can_valid', 'Rôle valideur'), ('can_publish', 'Rôle publieur')],
                'abstract': False,
            },
        ),
    ]
