# Generated by Django 5.0.3 on 2024-03-11 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_admin_workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SlugField(choices=[('DRAFT', 'draft')], default='DRAFT', max_length=8)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_admin_workflow.space', verbose_name='space')),
            ],
            options={
                'verbose_name': 'Analyse',
            },
        ),
    ]
