# Generated by Django 5.0.3 on 2024-03-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='creator',
            field=models.CharField(default='admin', max_length=40),
        ),
        migrations.AddField(
            model_name='analysis',
            name='space',
            field=models.CharField(default='default', max_length=40),
        ),
    ]
