# Generated by Django 5.0.3 on 2024-03-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_analysis_creator_analysis_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='creator',
            field=models.CharField(default='admin', editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='space',
            field=models.CharField(default='default', editable=False, max_length=40),
        ),
    ]
