# Generated by Django 5.0.3 on 2024-03-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_analysis_creator_alter_analysis_space'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name': 'Analyse'},
        ),
    ]
