# Generated by Django 5.0.3 on 2024-03-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_analysis_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='creator',
            field=models.CharField(default='admin', editable=False, max_length=40, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='space',
            field=models.CharField(default='default', editable=False, max_length=40, verbose_name='space'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('n', 'Nouveau'), ('s', 'Soumis'), ('a', 'Accepté'), ('v', 'Validé'), ('p', 'Publié'), ('c', 'Annulé')], default='n', max_length=1),
        ),
    ]
